CREATE TABLE addCv(
id VARCHAR PRIMARY KEY,
fullName VARCHAR NOT NULL,
age INTEGER NOT NULL,
currentAddress VARCHAR NOT NULL,
email VARCHAR UNIQUE NOT NULL,
phone VARCHAR UNIQUE NOT NULL,
job VARCHAR NOT NULL
);